### ISSUE TITLE
Snakemake --profile slurm --dry-run showing AttributeError

### ISSUE THREAD

**Issue by sm1216** [HelikarLab/FastqToGeneCounts#21]
Running a new setup of Snakemake shows the following errors

```
Traceback (most recent call last):
  File "/home/helikarlab/sabyasachi/.conda/envs/snakemake/lib/python3.10/site-packages/snakemake/__init__.py", line 701, in snakemake
    success = workflow.execute(
  File "/home/helikarlab/sabyasachi/.conda/envs/snakemake/lib/python3.10/site-packages/snakemake/workflow.py", line 1066, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/home/helikarlab/sabyasachi/.conda/envs/snakemake/lib/python3.10/site-packages/snakemake/dag.py", line 2191, in stats
    yield tabulate(rows, headers="keys")
  File "/home/helikarlab/sabyasachi/.conda/envs/snakemake/lib/python3.10/site-packages/tabulate/__init__.py", line 2048, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/home/helikarlab/sabyasachi/.conda/envs/snakemake/lib/python3.10/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/helikarlab/sabyasachi/.conda/envs/snakemake/lib/python3.10/site-packages/tabulate/__init__.py", line 1471, in <lambda>
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/helikarlab/sabyasachi/.conda/envs/snakemake/lib/python3.10/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
    (len(row) >= 1 and row[0] == SEPARATING_LINE)
  File "/home/helikarlab/sabyasachi/.conda/envs/snakemake/lib/python3.10/site-packages/snakemake/rules.py", line 1138, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'
```

**Comment by sm1216** [comment]
These are the SRR files I am using

```
SRR14759965,preB_S1R1,PE,total
SRR14759966,preB_S1R2,PE,total
SRR14759967,preB_S1R3,PE,total
SRR14759968,preB_S1R4,PE,total
```
